project:
  type: website
  output-dir: docs
freeze: auto

website:

  page-navigation: true
  reader-mode: true
  title: "MAT555E"
  description: "Homepage for MAT555E."
  site-url: "https://MAT555E-Fall22.github.io"
   
  repo-url: https://github.com/MAT555E-Fall22/MAT555E-Fall22.github.io
  repo-actions: [edit, issue] 
  
  page-footer:
    left: |
      This website is built with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=80px}](https://quarto.org/).
    right: "&copy; Copyright 2022, Gül İnan"

  sidebar: 
    logo: "images/logo.png"
    pinned: false
    align: center
    tools:
      - icon: github
        href: https://github.com/MAT555E-Fall22
      - icon: code-square
        href: https://ninova.itu.edu.tr/tr/
    style: "floating"
    search: true
    collapse-level: 0
    
    contents:
      - section: "**Course Information**"
        contents:
          - href: instructor.qmd
          - href: syllabus.qmd
      - section: "**Lecture Materials**"
        contents:
          - href: lectures/lec_01.qmd 
      - section: "**Lab Materials**"
        contents:
          - section: "Week 01"
            contents:
              - href: labs/Week_01_Eda_01.ipynb  
              - href: labs/Week_01_Eda_02.ipynb 
          
          
          
          
          
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    highlight-style: tango


